# Generated by Django 4.1.7 on 2023-03-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='films', to='app.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='films', to='app.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='films', to='app.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writters',
            field=models.ManyToManyField(related_name='films', to='app.writter'),
        ),
    ]
