# Generated by Django 4.1.7 on 2023-03-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
