# Generated by Django 4.1.7 on 2023-03-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='taken_seats',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
