# Generated by Django 4.1.7 on 2023-03-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_projection_taken_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('number_of_tickets', models.IntegerField()),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projection')),
            ],
        ),
    ]
