# Generated by Django 4.1.7 on 2023-03-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.movie'),
            preserve_default=False,
        ),
    ]
