# Generated by Django 4.1.7 on 2023-03-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reservation_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='movie',
        ),
    ]
