# Generated by Django 4.1.7 on 2023-03-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_reservation_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='available_seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='projection',
            name='taken_seats',
            field=models.IntegerField(default=0),
        ),
    ]
