# Generated by Django 4.1.7 on 2023-03-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_projection_available_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
